name: 'GitHub Actions Every 2 Minutes'

on:
  schedule:
    - cron: '*/2 * * * *'

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - name: 'Curl the api'
        run: curl https://jsonplaceholder.typicode.com/todos/1
