name: 'GitHub Actions Every 10 Minutes for herokuapp'

on:
  schedule:
    - cron: '*/10 * * * *'

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - name: 'Curl the api'
        run: curl algoload.herokuapp.com/
