name: 'GitHub Actions CURL Cron'

on:
  push:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: 'Curl the api'
        run: curl https://jsonplaceholder.typicode.com/todos/1
